### ISSUE TITLE
Add hover Effect on the add button and make the cursor pointer when hovering over the `Add` button

### ISSUE THREAD

**Issue by adnansam110** [Aryan-kumar-mains/To-Do-App#10]
@Aryan-kumar-mains Kindly assign this issue to me under hacktober fest label please

**Comment by Aryan-kumar-mains** [comment]
okay @adnansam110

**Comment by prashant5025** [comment]
@adnansam110  I like to contribute to this issue please assign it to me.

**Comment by adnansam110** [comment]
@prashant5025 I have already raised a PR for it. Try another issue. Thanks

**Comment by prashant5025** [comment]
Okay, Thank You.
