### ISSUE TITLE
Node modules are getting pushed.

### ISSUE THREAD

**Issue by HammadKhaan** [Aryan-kumar-mains/To-Do-App#12]
`node_modules` must be included in `.gitignore` file.

**Comment by HammadKhaan** [comment]
@Aryan-kumar-mains assign this issue to me.

**Comment by Aryan-kumar-mains** [comment]
go ahead @HammadKhaan

**Comment by HammadKhaan** [comment]
@Aryan-kumar-mains someone already created that `.gitignore` file and pushed it to master. You can close this issue.
