### ISSUE TITLE
Adding scrollbar for Todo Lists and enhancing design

### ISSUE THREAD

**Issue by mr-vijaychauhan** [Aryan-kumar-mains/To-Do-App#16]
- add Vertical Scrollbar for todolist 
- trying to fix other issue for UI so look nice

![TodoList-Hacktoberfest](https://user-images.githubusercontent.com/63604585/194102750-5bf067c7-75b7-4795-93b1-09824239d8da.png)

**Comment by Darainn** [comment]
@Aryan-kumar-mains assign me this issue as well

**Comment by Aryan-kumar-mains** [comment]
Okay @mr-vijaychauhan go ahead

**Comment by Aryan-kumar-mains** [comment]
@Darainn do that
