### ISSUE TITLE
Long Words overflowing from container

### ISSUE THREAD

**Issue by Amiyanshu-web** [Aryan-kumar-mains/To-Do-App#17]
Long words are getting overflown out of the box. Ideally, extra characters should move to the next line maintaining the spacing between text and buttons.
I would like to fix this issue.
![Screenshot (5)](https://user-images.githubusercontent.com/59080551/194115353-0b3637d2-05cd-476e-8edf-0c7fe5e75fd0.png)

**Comment by Darainn** [comment]
@Amiyanshu-web assign me this issue

**Comment by Aryan-kumar-mains** [comment]
@Darainn @Amiyanshu-web this issue is already solved, the page is not updated actually. That's why it is still showing.

Thanks for your interest.
