### ISSUE TITLE
[Feat] Add item on ENTER

### ISSUE THREAD

**Issue by mitpancholi98** [Aryan-kumar-mains/To-Do-App#20]
### Details

- Current: Empty item is added to list
- Expected: Item must be added after **trim**, and should be able to add on **enter key**.

![image](https://user-images.githubusercontent.com/51367069/194487532-4485bd63-532f-4150-809e-0254106255e2.png)

**Comment by mitpancholi98** [comment]
@Aryan-kumar-mains, what you say ?

**Comment by Aryan-kumar-mains** [comment]
adding an empty item is just fine, don't change it but add a feature of adding an item on ENTER key @mitpancholi98

**Comment by Aryan-kumar-mains** [comment]
and after doing it share the gif or short video.

**Comment by JawHawk** [comment]
@Aryan-kumar-mains  I can work on this enhancement, can you assign it to me too if possible .

**Comment by mitpancholi98** [comment]
@JawHawk you could take other issues, or as they say "create it / find it" ? 😁

**Comment by mitpancholi98** [comment]
> and after doing it share the gif or short video.

attached one in PR

**Comment by mitpancholi98** [comment]
Thanks @Aryan-kumar-mains. just to inform you, I think deployment is failing on heroku

**Comment by Aryan-kumar-mains** [comment]
Yes @mitpancholi98
