### ISSUE TITLE
Bug on creating a list

### ISSUE THREAD

**Issue by Aryan-kumar-mains** [Aryan-kumar-mains/To-Do-App#4]
there is a bug on creating a list with long word without any space 
For e.g. see the 2nd item in below screenshot .

![Screenshot (375)](https://user-images.githubusercontent.com/52608321/194036314-2b3d6ec8-fdca-4eb6-a3e9-63cde5f3e899.png)

**Comment by HammadKhaan** [comment]
@Aryan-kumar-mains assign this to me.

**Comment by Kunalpal215** [comment]
can you assign it to me ? what should be done to stop this overflowing ?

**Comment by Aryan-kumar-mains** [comment]
@HammadKhaan go ahead.

**Comment by Aryan-kumar-mains** [comment]
@Kunalpal215 This is already assigned, so either work on another issue or raise your issue.
